export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST';
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS';
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL';
export const STUDENT_CREATE_RESET = 'STUDENT_CREATE_RESET';